<?php if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_5d6fa8a18a33f',
        'title' => 'Archive',
        'fields' => array(
            array(
                'key' => 'field_5d6fa8ae0034a',
                'label' => 'File URL',
                'name' => 'archive_file_url',
                'type' => 'file',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'archive',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d722f6643568',
        'title' => 'Category',
        'fields' => array(
            array(
                'key' => 'field_5d722fbc0784a',
                'label' => 'Logo',
                'name' => 'category_logo',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5d722fd80784b',
                'label' => 'Title',
                'name' => 'category_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5dad4fb0064d8',
                'label' => 'themes',
                'name' => 'theme_botton',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    '{"secondary_color":"#2DEBAE","sidebar_header":"#2DA89C","sidebar_body":"#004365","header":"#112539","body":"#004365","scroll":"#6c757d","scroll_track":"#343a40","minimize_tabs":"#FFFFFF","notification":"#FF0000","sidebar_text":"#ffffff","sidebar_content_heading":"#000","minimize_tab_text":"#fff","sidebar_plus_sign":"#2DEBAE"}' => '<img    src="https://slackthemes.net/images/theme/socialsign_in-dbdfda13d68bc537558673eefddfa685.png" height="100px" width="150px" align="center" style="object-fit: contain;">',
                    '{"secondary_color":"#F6756D","sidebar_header":"#232B38","sidebar_body":"#325180","header":"#1A2535","body":"#27364E","scroll":"#E6E6E9","scroll_track":"#a8a8e6","minimize_tabs":"#F55D54","notification":"#c7271e","sidebar_text":"#ffffff","sidebar_content_heading":"#FFF","minimize_tab_text":"#fff","sidebar_plus_sign":"#F55D54"}' => '<img    src="https://slackthemes.net/images/theme/mockingbot-69cd3dd7a2bf4732a5b53ba291dd013f.png" height="100px" width="150px" align="center" style="object-fit: contain; ">',
                    '{"secondary_color":"#889962","sidebar_header":"#B65F49","sidebar_body":"#181818","header":"#181818","body":"#384048","scroll":"#E6E6E9","scroll_track":"#a8a8e6","minimize_tabs":"#81A9C2","notification":"#A79AC6","sidebar_text":"#fff","sidebar_content_heading":"#A79AC6","minimize_tab_text":"#fff","sidebar_plus_sign":"#889962"}' => '<img src="https://slackthemes.net/images/theme/jellybeans-c949f124871e1e321075dfe68c6beb47.png" height="100px" width="150px" align="center" style="object-fit: contain; margin-top:10px;">',
                    '{"secondary_color":"#64FCDA","sidebar_header":"#263238","sidebar_body":"#546E7A","header":"#546E7A","body":"#546E7A","scroll":"#ECEFF1","scroll_track":"#a8a8e6","minimize_tabs":"#40C4FF","notification":"#FF5252","sidebar_text":"#fff","sidebar_content_heading":"#FFFFFF","minimize_tab_text":"#fff","sidebar_plus_sign":"#FF5252"}' => '<img    src="https://slackthemes.net/images/theme/material-87388ffc7f65ab8a8e374e5e57be2ab5.png" height="100px" width="150px" align="center" style="object-fit: contain; margin-top:10px;">',
                    '{"secondary_color":"#EB4864","sidebar_header":"#211d36","sidebar_body":"#383643","header":"#211f2e","body":"#211d36","scroll":"#ECEFF1","scroll_track":"#a8a8e6","minimize_tabs":"#FFFFFF","notification":"#b30523","sidebar_text":"#fff","sidebar_content_heading":"#FFFFFF","minimize_tab_text":"#000","sidebar_plus_sign":"#EB4864"}' => '<img    src="https://slackthemes.net/images/theme/hibari-a56ea39af6547d6ea1b520cad336aba2.png" height="100px" width="150px" align="center" style="object-fit: contain; margin-top:10px;">',
                    '{"secondary_color":"#EDB54B","sidebar_header":"#2c3a4a","sidebar_body":"#0A0F14","header":"#0A0F14","body":"#2c3a4a","scroll":"#ECEFF1","scroll_track":"#a8a8e6","minimize_tabs":"#C33027","notification":"#C33027","sidebar_text":"#9BD1CE","sidebar_content_heading":"#fff","minimize_tab_text":"#000","sidebar_plus_sign":"#265360"}' => '<img    src="https://slackthemes.net/images/theme/gotham-4a90892a1ccb6a3f5a0aaeff2a21da4f.png" height="100px" width="150px" align="center" style="object-fit: contain; margin-top:10px;">',
                    '{"secondary_color":"#57d49b","sidebar_header":"#42B983","sidebar_body":"#4d394b","header":"#222f3d","body":"#34495E","scroll":"#ECEFF1","scroll_track":"#a8a8e6","minimize_tabs":"#C33027","notification":"#FFD41D","sidebar_text":"#fff","sidebar_content_heading":"#FFF","minimize_tab_text":"#000","sidebar_plus_sign":"#FFD41D"}' => '<img src = "https://slackthemes.net/images/theme/vue_js-dacadade5fdd423e05ce0414761341cb.png" height="100px" width="150px" align="center" style="object-fit: contain; margin-top:10px;">',
                    '{"secondary_color":"#5AE043","sidebar_header":"#157477","sidebar_body":"#4d394b","header":"#4d394b","body":"#444444","scroll":"#ECEFF1","scroll_track":"#a8a8e6","minimize_tabs":"#888888","notification":"#1DE2E7","sidebar_text":"#fff","sidebar_content_heading":"#FFF","minimize_tab_text":"#000","sidebar_plus_sign":"#5AE043"}' => '<img   src="https://slackthemes.net/images/theme/nitro_marketing_digital-760bfd95284a88080ef268a4166d4cd3.png" height="100px" width="150px" align="center" style="object-fit: contain; margin-top:10px;">',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'category',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5db04c85b2074',
        'title' => 'Stock code',
        'fields' => array(
            array(
                'key' => 'field_5db04c8e09637',
                'label' => 'Stock Symbol',
                'name' => 'stock_symbol',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'category',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));


    acf_add_local_field_group(array(
        'key' => 'group_5d722f6643568',
        'title' => 'Category',
        'fields' => array(
            array(
                'key' => 'field_5d722fbc0784a',
                'label' => 'Logo',
                'name' => 'category_logo',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5d722fd80784b',
                'label' => 'Title',
                'name' => 'category_title',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5dad5802dd581',
                'label' => 'themes',
                'name' => 'theme_botton',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    '{"secondary_color":"#2DEBAE","sidebar_header":"#2DA89C","sidebar_body":"#004365","header":"#112539","body":"#004365","scroll":"#6c757d","scroll_track":"#343a40","minimize_tabs":"#FFFFFF","notification":"#FF0000","sidebar_text":"#ffffff","sidebar_content_heading":"#000","minimize_tab_text":"#fff","sidebar_plus_sign":"#2DEBAE"}' => '<img	src="https://decidigital.com/wp-content/uploads/2017/06/1tampawebdesign.jpg" height="80px" width="200px" align="center">',
                    '{"secondary_color":"#F6756D","sidebar_header":"#232b38","sidebar_body":"#325180","header":"#1A2535","body":"#27364E","scroll":"#E6E6E9","scroll_track":"#a8a8e6","minimize_tabs":"#F55D54","notification":"#c7271e","sidebar_content_heading":"#FFFFFF","sidebar_plus_sign":"#F55D54"}' => '<img	src="https://cdn.richtabor.com/wp-content/uploads/2017/09/designing-868x621.jpg" height="80px" width="200px" align="center">',
                ),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => '',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'category',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d6fa4f1dc976',
        'title' => 'Contact',
        'fields' => array(
            array(
                'key' => 'field_5d722b365ff7e',
                'label' => 'Contact details',
                'name' => 'contact_details',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_5d722b5f5ff7f',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5d722b5f5ff7f',
                        'label' => 'Full Name',
                        'name' => 'contact_name',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5d722bfd5ff86',
                        'label' => 'Designation',
                        'name' => 'designation',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5d722b6f5ff80',
                        'label' => 'Picture',
                        'name' => 'contact_picture',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => array(
                            array(
                                array(
                                    'field' => 'field_5d722b365ff7e',
                                    'operator' => '!=empty',
                                ),
                            ),
                        ),
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                    array(
                        'key' => 'field_5d722b8f5ff81',
                        'label' => 'Instagram',
                        'name' => 'instagram',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5d72456a9fd99',
                        'label' => 'Twitter',
                        'name' => 'twitter',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5d7245819fd9a',
                        'label' => 'Facebook',
                        'name' => 'facebook',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5d8db086ffd9f',
                        'label' => 'LinkdIn',
                        'name' => 'linkdin',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5d7245919fd9b',
                        'label' => 'E-Mail',
                        'name' => 'email',
                        'type' => 'email',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'contact',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d95a27e0d012',
        'title' => 'dashboard',
        'fields' => array(
            array(
                'key' => 'field_5d95a2870a47c',
                'label' => 'dashboard',
                'name' => 'dashboard',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'hud' => 'hud',
                    'metro' => 'metro',
                ),
                'default_value' => array(),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'taxonomy',
                    'operator' => '==',
                    'value' => 'category',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d70a67967742',
        'title' => 'Gallery',
        'fields' => array(
            array(
                'key' => 'field_5d70a67fb7a5e',
                'label' => 'Photos',
                'name' => 'photos',
                'type' => 'gallery',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'medium',
                'insert' => 'append',
                'library' => 'all',
                'min' => '',
                'max' => '',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'gallery',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d91e677c4f5b',
        'title' => 'insights',
        'fields' => array(
            array(
                'key' => 'field_5d971a846b18e',
                'label' => 'size',
                'name' => 'size',
                'type' => 'select',
                'instructions' => 'select sze to display.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'chart-span-1' => 'small',
                    'chart-span-2' => 'medium',
                    'chart-span-3' => 'lagre',
                ),
                'default_value' => array(
                    0 => 'small',
                ),
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'insights',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d89c700e9cce',
        'title' => 'Line Chart',
        'fields' => array(),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'insight',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d6fa65112eac',
        'title' => 'Link',
        'fields' => array(
            array(
                'key' => 'field_5d6fa66e4fbed',
                'label' => 'Link details',
                'name' => 'link_details',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5d722c8ad2ee2',
                        'label' => 'Platform',
                        'name' => 'link_platform',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5d722c9ad2ee3',
                        'label' => 'Link',
                        'name' => 'link',
                        'type' => 'url',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_5d722cabd2ee4',
                        'label' => 'Icon',
                        'name' => 'link_icon',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'fa-facebook' => 'Facebook',
                            'fa-instagram' => 'Instagram',
                            'fa-wikipedia-w' => 'Wikipedia',
                            'fa-twitter' => 'Twitter',
                            'fa-youtube' => 'Youtube',
                            'fa-angellist' => 'Angellist',
                            'fa-tumblr' => 'Tumblr',
                            'fa-snapchat' => 'Snapchat',
                            'fa-pinterest' => 'Pinterest',
                            'fa-linkedin' => 'LinkdIn',
                            'fa-globe' => 'Website',
                        ),
                        'default_value' => array(),
                        'allow_null' => 0,
                        'multiple' => 0,
                        'ui' => 0,
                        'return_format' => 'value',
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'link',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d6fa1bcb0c24',
        'title' => 'Map',
        'fields' => array(
            array(
                'key' => 'field_5d6fa1cb12305',
                'label' => 'Map details',
                'name' => 'map_details',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5d721db8fbec4',
                        'label' => 'Name',
                        'name' => 'map_name',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'Map name',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5d721dd2fbec5',
                        'label' => 'Coordinates',
                        'name' => 'map_coordinates',
                        'type' => 'google_map',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'center_lat' => '',
                        'center_lng' => '',
                        'zoom' => '',
                        'height' => '',
                    ),
                    array(
                        'key' => 'field_5d721dedfbec6',
                        'label' => 'Content',
                        'name' => 'map_content',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5d721e0efbec7',
                        'label' => 'Color',
                        'name' => 'map_color',
                        'type' => 'color_picker',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'map',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d6fa105507e5',
        'title' => 'Millestone',
        'fields' => array(
            array(
                'key' => 'field_5d6fa10f7b3ef',
                'label' => 'Timeline details',
                'name' => 'timeline_details',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => 'field_5d72075ffc14d',
                'min' => 0,
                'max' => 0,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5d72075ffc14d',
                        'label' => 'Title',
                        'name' => 'timeline_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5d72079cfc14e',
                        'label' => 'Content',
                        'name' => 'timeline_content',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                    array(
                        'key' => 'field_5d72081738e21',
                        'label' => 'Year',
                        'name' => 'timeline_year',
                        'type' => 'number',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'min' => 1500,
                        'max' => 2100,
                        'step' => 1,
                    ),
                    array(
                        'key' => 'field_5d7208693e68d',
                        'label' => 'Icon',
                        'name' => 'timeline_favicon',
                        'type' => 'image',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                        'preview_size' => 'thumbnail',
                        'library' => 'all',
                        'min_width' => '',
                        'min_height' => '',
                        'min_size' => '',
                        'max_width' => '',
                        'max_height' => '',
                        'max_size' => '',
                        'mime_types' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'timeline',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d71ebbbccc09',
        'title' => 'Tab',
        'fields' => array(
            array(
                'key' => 'field_5d71ebc03f3c6',
                'label' => 'Tab',
                'name' => 'tab',
                'type' => 'repeater',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 1,
                'max' => 4,
                'layout' => 'row',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5d71ebd23f3c7',
                        'label' => 'Tab title',
                        'name' => 'tab_title',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5d71ebea3f3c8',
                        'label' => 'Tab content',
                        'name' => 'tab_content',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'maxlength' => '',
                        'rows' => '',
                        'new_lines' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'tab',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d6fa83e00162',
        'title' => 'Video',
        'fields' => array(
            array(
                'key' => 'field_5d6fa84537f9c',
                'label' => 'Duration',
                'name' => 'video_duration',
                'type' => 'time_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'H:i',
                'return_format' => 'H:i',
            ),
            array(
                'key' => 'field_5d75da4a99407',
                'label' => 'Video file',
                'name' => 'video_file',
                'type' => 'file',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'video',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d6fa91eedbe0',
        'title' => 'Webinar',
        'fields' => array(
            array(
                'key' => 'field_5d6fa92e0ba49',
                'label' => 'Duration',
                'name' => 'webinar_duration',
                'type' => 'time_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'g:i a',
                'return_format' => 'g:i a',
            ),
            array(
                'key' => 'field_5d72371ad6983',
                'label' => 'Presenter Name',
                'name' => 'presenter_name',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5d73669f1a0b9',
                'label' => 'URL',
                'name' => 'webinar_url',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
            array(
                'key' => 'field_5d8dd9aebabc3',
                'label' => 'Webinar Schedule',
                'name' => 'webinar_schedule',
                'type' => 'date_time_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'F j, Y g:i a',
                'return_format' => 'F j, Y g:i a',
                'first_day' => 1,
            ),
            array(
                'key' => 'field_5d8dda2ebabc4',
                'label' => 'Venue',
                'name' => 'venue',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5d8dda5ebabc5',
                'label' => 'Timezone',
                'name' => 'timezone',
                'type' => 'date_time_picker',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'display_format' => 'd/m/Y g:i a',
                'return_format' => 'd/m/Y g:i a',
                'first_day' => 1,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'webinar',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d6fa759aeb79',
        'title' => 'Podcast',
        'fields' => array(
            array(
                'key' => 'field_5d75daa2d467b',
                'label' => 'Audio file',
                'name' => 'audio_file',
                'type' => 'file',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'url',
                'library' => 'all',
                'min_size' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'podcast',
                ),
            ),
        ),
        'menu_order' => 1,
        'position' => 'acf_after_title',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => array(
            0 => 'excerpt',
        ),
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5d8af1f3315b1',
        'title' => 'Visualizer',
        'fields' => array(
            array(
                'key' => 'field_5d8af20027516',
                'label' => 'Visualizer',
                'name' => 'visualizer',
                'type' => 'wysiwyg',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'delay' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'insights',
                ),
            ),
        ),
        'menu_order' => 1,
        'position' => 'side',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

endif;
